---
title: "Enrichment NB 04: Using rSEA to analyze pathway enrichment for CPTAC CNV data"
author: "Caleb Lindgren"
---

# Enrichment NB 04: Using rSEA to analyze pathway enrichment for CPTAC CNV data

## Setup

```{r, message=FALSE}
library(tidyverse)
library(rSEA)

THRESHOLDS = seq(0.1, 0.9, by = 0.1) 

INPUT_DIR <- "protein_groups"
INPUT_FILE <- "groups_proteins.tsv.gz"
INPUT_FILE_PATH <- file.path(INPUT_DIR, INPUT_FILE)

PATHWAYS_DIR <- "gene_set_libraries"
PATHWAYS_FILE <- "GO_Biological_Process_2018.gmt"
PATHWAYS_FILE_PATH <- file.path(PATHWAYS_DIR, PATHWAYS_FILE)

OUTPUT_DIR <- "04_rSEA_results"

# Create the output directory if it doesn't already exist
dir.create(OUTPUT_DIR, showWarnings = FALSE)
```

## Step 1: Load expression data and divide by cancer type and group

```{r, message=FALSE, warning=FALSE}
all_expr_data <- read_tsv(INPUT_FILE_PATH)
groups <- distinct(all_expr_data, cancer_type_group)$cancer_type_group
split_expr_data <- lapply(groups, function(x) filter(all_expr_data, cancer_type_group == x))
names(split_expr_data) <- groups
```

## Step 2: Load pathway lists

```{r}
pathways <- PATHWAYS_FILE_PATH %>%
  readLines() %>% # Read in each line of the file as a string
  sapply(strsplit, split = "\t") # Split each line on the tab character

pathway_ids <- sapply(pathways, function(x) x[[1]]) # Save the pathway ids
pathways <- sapply(pathways, function(x) x[-(1:2)]) # Cut out the pathway names and blank id spot from the lists
names(pathways) <- pathway_ids # Set the pathway ids as the names
```

## Step 3: Run rSEA and save the results
```{r}
for (threshold in THRESHOLDS) {
  results <- lapply(split_expr_data, function(x) SEA(
    pvalue = x$adj_p,
    featureIDs = x$protein_str,
    pathlist = pathways,
    thresh = threshold,
    competitive = FALSE))
  
  names(results) <- groups
  
  results <- groups %>%
    lapply(function(x) results[[x]] %>% add_column(cancer_type_group = x)) %>% # Add each table's cancer type group as a column
    bind_rows() # Combine all the tables into one table
  
  OUTPUT_FILE_PATH <- file.path(
    OUTPUT_DIR,
    paste("enrichment_rsea_thresh_", threshold, ".tsv", sep = ""))
  
  write_tsv(results, OUTPUT_FILE_PATH)
}
```